
export default {
  ADR: 	{ desc: 'Street address', color: 'red'},
  ANM: 	{ desc: 'Animal', color: 'pink'},
  BLD: 	{ desc: 'Building', color: 'purple'},
  COM: 	{ desc: 'Company, business', color: 'deep-purple'},
  DAT: 	{ desc: 'Date', color: 'indigo'},
  DEV: 	{ desc: 'Device', color: 'blue'},
  DOC: 	{ desc: 'Document', color: 'light-blue'},
  EVN: 	{ desc: 'Event', color: 'cyan'},
  FDD: 	{ desc: 'Food, beverage', color: 'teal'},
  GEA: 	{ desc: 'Physical geographic feature', color: 'green'},
  GEO: 	{ desc: 'Administrative geographic area', color: 'light-green'},
  GEX: 	{ desc: 'Extended geography', color: 'orange'},
  HOU: 	{ desc: 'Hours', color: 'deep-orange'},
  LEN: 	{ desc: 'Legal entity', color: 'brown'},
  MAI: 	{ desc: 'Email address', color: 'grey'},
  MEA: 	{ desc: 'Measure', color: 'blue-grey'},

  MMD: 	{ desc: 'Mass media', color: 'red-10'},
  MON: 	{ desc: 'Money', color: 'pink-10'},
  NPH: 	{ desc: 'Person', color: 'purple-10'},
  NPR: 	{ desc: 'Unrecognized entity with a proper noun', color: 'deep-purple-10'},
  ORG: 	{ desc: 'Organization, institution, society', color: 'indigo-10'},
  PCT: 	{ desc: 'Percentage', color: 'blue-10'},
  PHO: 	{ desc: 'Phone number', color: 'light-blue-10'},
  PPH: 	{ desc: 'Physical phenomena', color: 'cyan-10'},
  PRD: 	{ desc: 'Product', color: 'teal-10'},
  VCL: 	{ desc: 'Vehicle', color: 'green-10'},
  WEB: 	{ desc: 'Web address', color: 'light-green-10'},
  WRK: 	{ desc: 'Work of human intelligence', color: 'orange-10'},
}
